# sweep.yaml
method: bayes  # 或者 grid/random
metric:
  name: eval/f1
  goal: maximize

parameters:
  lora_r:
    values: [4, 8, 16]

  lora_alpha:
    values: [16, 32, 64]

  lora_dropout:
    values: [0.05, 0.1, 0.2]

  lr:
    values: [1e-5, 3e-5, 5e-5]

  batch_size:
    values: [16, 32]
  num_epochs:
    value: 10 